name: Refresh README

on:
  schedule:
    - cron: '*/30 * * * *'   # har 30 min chalane ke liye (testing ke liye kam rakho)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update README
        run: |
          echo "Last refresh: $(date)" >> README.md
          git add README.md
          git commit -m "Auto update README"
          git push
